export default{
    SUBMIT_SEARCH:'SUBMIT_SEARCH',
    FETCH_TWEET: 'FETCH_TWEET',
    FETCH_TWEETS: 'FETCH_TWEETS',
    SET_TWEET: 'SET_TWEET',
    SUBMIT_USER: 'SUBMIT_USER',
    FETCH_BOTSCORE: 'FETCH_BOTSCORE'
}